let products = [
    {
        "id": 1001,
        "title": "Maths",
        "location": "London",
        "price": 25,
        "image": "https://icons-for-free.com/iconfiles/png/512/math+tutor+icon-1320195955563127435.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1002,
        "title": "English",
        "location": "Birmingham",
        "price": 20,
        "image": "https://icons-for-free.com/iconfiles/png/512/design+edit+line+pen+pencil+write+icon-1320087227670474737.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1003,
        "title": "Science",
        "location": "Manchester",
        "price": 25,
        "image": "https://icons-for-free.com/iconfiles/png/512/cube+culture+experiment+lab+laboratory+icon-1320184206497855582.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1004,
        "title": "Geography",
        "location": "Leeds",
        "price": 15,
        "image": "https://icons-for-free.com/iconfiles/png/512/history+tutor+world+globe+icon-1320195955885841255.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1005,
        "title": "History",
        "location": "Cardiff",
        "price": 30,
        "image": "https://icons-for-free.com/iconfiles/png/512/books+documents+files+folders+history+icon-1320167910366443137.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1006,
        "title": "ICT",
        "location": "Glasgow",
        "price": 10,
        "image": "https://icons-for-free.com/iconfiles/png/512/laptop+notebook+screen+technology+icon-1320168142184944588.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1007,
        "title": "Law",
        "location": "Liverpool",
        "price": 40,
        "image": "https://icons-for-free.com/iconfiles/png/512/auction+finance+gavel+hammer+justice+law+icon-1320086007250407801.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1008,
        "title": "Economics",
        "location": "Edinburgh",
        "price": 45,
        "image": "https://icons-for-free.com/iconfiles/png/512/money+payment+purchase+shopping+transaction+icon-1320166003047302161.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1009,
        "title": "Spanish",
        "location": "York",
        "price": 17,
        "image": "https://cdn1.iconfinder.com/data/icons/flags-of-the-world-2/128/spain-circle-512.png",
        "availableInventory": 10,
        "rating":3,
    },
    {
        "id": 1010,
        "title": "Psychology",
        "location": "Bath",
        "price": 13,
        "image": "https://icon-library.com/images/brain-icon-flat/brain-icon-flat-18.jpg",
        "availableInventory": 10,
        "rating":3,
    },
]